/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mam' at '5/12/16 8:37 PM' with Gradle 2.11
 *
 * @author mam, @date 5/12/16 8:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
